version: '3.8'
services:
  db:
    image: postgres:15
    container_name: clear-ledger-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clear-ledger
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      target: production
    container_name: clear-ledger-app
    restart: always
    environment:
      NODE_ENV: production
      LOG_LEVEL: 'debug, verbose'
      DATABASE_URL: postgresql://postgres:root@clear-ledger-db:5432/clear-ledger?schema=public
      POPPLER_BIN_PATH: /usr/bin
      OPENAI_API_KEY: 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
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
    name: clear-ledger-data
networks:
  clear_ledger_network:
    name: clear_ledger_network
